Metrics/CyclomaticComplexity:
  Max: 999 #16

Metrics/PerceivedComplexity:
  Max: 999 #10

Metrics/AbcSize:
  Max: 999 #30

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Layout/CaseIndentation:
  IndentOneStep: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BracesAroundHashParameters:
  EnforcedStyle: braces

Style/RedundantBegin:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Next:
  Enabled: false
