dist: xenial

language: python

env:
  global:
    - CC_TEST_REPORTER_ID=6fd9c710b9a6e0da2011c62b81075b9bd620200a2a400f4dbeab9c88829f4cb6

python:
  - "3.7"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover
  - python setup.py sdist
  - python setup.py bdist_wheel

after_script:
  - coverage xml
  - ./cc-test-reporter after-build

notifications:
  email:
    on_success: never
