dist: xenial

language: python
python:
  - "3.7"
  - "3.8-dev"

install:
  - pip install -r requirements.txt --ignore-requires-pytho

script: python -m unittest

notifications:
  email:
    on_success: never
    on_failure: never
