#!/usr/bin/env bash

rm docker-requirements.text
echo "# This file is auto-generated by build_requirements.sh" > docker-requirements.text
echo "# Please do not edit this file manually" >> docker-requirements.text
pipenv requirements --dev >> docker-requirements.text
