# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yawast-ng ...where a pentest starts
email: adam@adamcaudill.com
description: >- # this means to ignore newlines until "baseurl:"
  yawast-ng is an application meant to simplify initial analysis and information gathering
  for penetration testers and security auditors.
baseurl: "/yawast-ng" # the subpath of your site, e.g. /blog
url: "https://numorian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "https://github.com/Numorian/yawast-ng/raw/main/yawast_logo_v1.svg?sanitize=true"
github_username:  Numorian
author: 'Adam Caudill'

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "/"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

permalink: /blog/:year/:month/:day/:title/
