# build /docs using bundle install && bundle exec jekyll build
name: Build Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        working-directory: ./docs
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        working-directory: ./docs
        run: |
          bundle exec jekyll build
