name: build-python-package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Info - Github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Debug Info - Env
      run: set
      shell: bash {0}

    - name: Debug Info - Runner
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv sync --dev
      shell: bash {0}

    - name: Setup Selenium (Linux)
      if: runner.os == 'Linux'
      run: |
        echo 'export PATH="/home/runner/work/yawast/yawast:$PATH"' >> ~/.bashrc
        echo PATH=/home/runner/work/yawast/yawast:$PATH >> .env
        export PATH="/home/runner/work/yawast/yawast:$PATH"
        echo $PATH
        which chromedriver
      shell: bash {0}

    - name: Run unit tests
      if: always()
      run: |
        pipenv install codecov
        pipenv run coverage run -m unittest discover
        pipenv run coverage xml
      shell: bash {0}

    - name: Upload results to Codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build packages
      if: always()
      run: |
        pipenv run python setup.py sdist
        pipenv run python setup.py bdist_wheel
      shell: bash {0}

    - name: Run version (all)
      if: always()
      run: |
        pipenv run python ./bin/yawast-ng version
      shell: bash {0}

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      if: github.ref != 'refs/heads/main'
      run: docker build . --file Dockerfile --tag yawast-ci:$(date +%s)
