name: Python install with pipx

on:
  schedule:
  - cron: 0 2 * * *

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath

    - name: Install with pipx
      run: |
        source ~/.profile
        pipx install --python python3.7 yawast --verbose
      shell: bash {0}

    - name: Run version
      run: |
        source ~/.profile
        yawast version
      shell: bash {0}
